package fan.md.model.relation;

public enum RelationType {
	FILE_CONTAIN_TYPE, PACKAGE_CONTAIN_FILE, 
	TYPE_CONTAINS_FUNCTION, FUNCTION_CALL_FUNCTION, TYPE_EXTENDS_TYPE, TYPE_IMPLEMENTS_TYPE,
	FILE_CONTAIN_FUNCTION;
}
