package fan.md.model.relation;

public enum RelationType {
	PACKAGE_CONTAINS_FILE, 
	
	FILE_CONTAINS_TYPE, 
	FILE_CONTAINS_FUNCTION, 
	
	TYPE_CONTAINS_FUNCTION, 
	TYPE_EXTENDS_TYPE, 
	TYPE_IMPLEMENTS_TYPE,
	
	FUNCTION_CALL_FUNCTION, 
	FUNCTION_RETURN_TYPE,
	FUNCTION_PARAMETER_TYPE,
	
	DYNAMIC_FUNCTION_CALL_FUNCTION;
	
}
