spring:
  data:
    neo4j:
      username: neo4j
      password: admin
#      uri: bolt://localhost:7687
#      uri: http://localhost:7474
      # embedded
      uri: file:///C:/ProgramLocal/neo4j/neo4j-community-3.5.14/data/databases/multi-dependency.db
server:
   port: 8080
   
data:
   code:
#      path: D:\git\halo-1.1.3-beta.1
#      path: D:\git\eclipse-workspace\test
      path: D:\Workspace\Architecture\multi-dependency
      language: java
#      path: D:\git\bcrypt-1.1
#      language: cpp
      platform: windows
   dynamic:
      analyse: true
      directory_root_path: src/main/resources/dynamic/kieker
#      directory_root_path: src/main/resources/dynamic/valgrind
      dynamic_java_file_suffix: [.dat]
      dynamic_cpp_file_suffix: [.dot, .out]
      dynamic_mark_suffix: .mark
   build:   
      analyse: true
      directory_root_path: src/main/resources/build
   neo4j:
      # batchInserter要插入的数据库
      path: C:/ProgramLocal/neo4j/neo4j-community-3.5.14/data/databases/multi-dependency.db
   
   test: this property is for YamlUtilsTest
      