spring:
  data:
    neo4j:
      username: neo4j
      password: 19970129Fan
      uri: bolt://localhost:7687
#      uri: http://localhost:7474
      # embedded
#      uri: file:///D:/fan/Users/Thinkpad/neo4j-community-3.5.3-windows/neo4j-community-3.5.3/data/databases/multiple.dependency.db
server:
   port: 8080
   
data:
   code:
#      path: D:\git\halo-1.1.3-beta.1
#      path: D:\git\eclipse-workspace\test
#      path: D:\git\multi-dependency
#      path: C:\Users\Thinkpad\Desktop\0416\all\cassandra-3.0.0\cassandra-cassandra-3.0.0
#      path: D:\multiple-dependency-project\apache-openoffice-4.1.7-46059c9192-src
#      path: C:\Users\fan\Downloads\hadoop-trunk
#      path: C:\Users\fan\Downloads\cassandra-trunk\cassandra-trunk
#      path: C:\Users\fan\Downloads\Compressed\kafka-2.4.0
#      path: D:\multiple-dependency-project\depends-0.9.5c
#      language: java
#      path: D:\git\bcrypt-1.1
#      path: D:\git\Sockets-2.3.9.9
#      path: D:\git\redis-5.0.5
#      path: D:\multiple-dependency-project\Sockets-2.3.9.9
      path: D:\multiple-dependency-project\bash-5.0
      language: cpp
      platform: windows
   dynamic:
#      directory_root_path: src/main/resources/dynamic/kieker
      directory_root_path: src/main/resources/dynamic/valgrind
      dynamic_java_file_suffix: [.dat]
      dynamic_cpp_file_suffix: [.dot, .out]
      dynamic_mark_suffix: .mark
   neo4j:
      # batchInserter要插入的数据库
      path: D:/neo4j-community-3.5.3-windows/neo4j-community-3.5.3/data/databases/multiple.dependency.db
   
   test: this property is for YamlUtilsTest
     
