spring:
  data:
    neo4j:
      username: neo4j
      password: neo4j
#      uri: bolt://localhost:7687
#      uri: http://localhost:7474
      # embedded
      uri: file:///fan/Users/Thinkpad/neo4j-community-3.5.3-windows/neo4j-community-3.5.3/data/databases/multiple.dependency.db
server:
   port: 8080
   
data:
   code:
#      path: D:\git\halo-1.1.3-beta.1
#      path: D:\git\eclipse-workspace\test
      path: D:\git\eclipse-workspace\multiple.dependency
      language: java
#      path: D:\git\bcrypt-1.1
#      language: cpp
      platform: windows
   dynamic:
      directory_root_path: src/main/resources/dynamic/kieker
#      directory_root_path: src/main/resources/dynamic/valgrind
      dynamic_java_file_suffix: [.dat]
      dynamic_cpp_file_suffix: [.dot]
      dynamic_mark_suffix: .mark
   neo4j:
      # batchInserter要插入的数据库
      path: D:\fan\Users\Thinkpad\neo4j-community-3.5.3-windows\neo4j-community-3.5.3\data\databases\multiple.dependency.db
   
   test: this property is for YamlUtilsTest
      