spring:
  data:
    neo4j:
      username: neo4j
      password: 19970129Fan
      uri: bolt://localhost:7687
#      uri: http://localhost:7474
      # embedded
#      uri: file:///D:/neo4j-community-3.5.3-windows/neo4j-community-3.5.3/data/databases/multiple.dependency.db
  thymeleaf:
    cache: false 
    prefix: classpath:/templates/
    suffix: .html
server:
   port: 8080

data:
#   project_config: src/main/resources/project/simpletest.json
#   project_config: src/main/resources/project/train-ticket_fan.json
#   project_config: src/main/resources/project/leveldb.json
   project_config: src/main/resources/project/source-fan-part.json
   dynamic_analyse: false
   git_analyse: false
   lib_analyse: false
   clone_analyse: true
   neo4j:
      delete: true
      # batchInserter要插入的数据库
#      path: D:/neo4j-community-3.5.3-windows/neo4j-community-3.5.3/data/databases/multiple.dependency.db
      path: D:/neo4j-community-3.5.16/data/databases/multiple.dependency.db
      
   serialize_path: D:/multiple-dependency-project/RepositoryService.txt
   
   test: this property is for YamlUtilsTest
