spring:
  data:
    neo4j:
      username: neo4j
      password: root
      uri: bolt://localhost:7687
      #uri: bolt://10.176.34.86:9687
      #uri: bolt://10.176.34.83:7687

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8995

config:
  starter:
    cochange: false
    depends_on: true
    clone_group: false
    module_clone: false
    aggregation_clone: false
    smell: false
    modularity: false
    export_cyclic_dependency : false
    coupling: true

data:
  project_analyse_threads_count: -1
  project_config: /home/fdse/code-wisdom-installer/services/dependence-analysis/neo4j/issue-tracker-master-linux.json
  dynamic_analyse: false
  git_analyse: false
  lib_analyse: false
  clone_analyse: false


  neo4j:
    delete: true
    data_path: /home/fdse/code-wisdom-installer/services/dependence-analysis/neo4j/neo4j-community-4.2.3/data
    database_name: issue-tracker.db

  serialize_path: /home/fdse/code-wisdom-installer/services/dependence-analysis/neo4j/RepositoryService-source-issue-tracker.txt
  anonymization : true

  test: this property is for YamlUtilsTest
