spring:
  data:
    neo4j:
      username: neo4j
      password: admin
      uri: bolt://10.176.34.96:7687
      #uri: bolt://10.176.34.86:9687
      #uri: bolt://10.176.34.83:7687

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8080

config:
  starter:
    insert_nodes: true
    insert_relations: true
    cochange: false
    depends_on: true
    clone_group: false
    module_clone: false
    aggregation_clone: false
    smell: false
    modularity: false
    coupling: true
    package_depth: true
    export_cyclic_dependency: false

data:
  project_analyse_threads_count: 20
  project_config: src/main/resources/project/issue-tracker-master.json
  dynamic_analyse: false
  git_analyse: false
  lib_analyse: false
  clone_analyse: false
  alltag_analyse: false
  diff_analyse: false
  snapshot_analyse: false

  neo4j:
    delete: true
    data_path: /Users/keyon/Documents/bigDataPlatform/depend-service/neo4j/data
    database_name: issue-tracker.db

  serialize_path: /Users/keyon/Documents/bigDataPlatform/depend-service/RepositoryService-source-issue-tracker.txt
  anonymization : true
  batch_serialize: true

  test: this property is for YamlUtilsTest
