spring:
  data:
    neo4j:
      username: neo4j
      password: 123456
      uri: bolt://localhost:7687
      #      uri: http://localhost:7474
      # embedded
  #      uri: file:///D:/neo4j-community-3.5.3-windows/neo4j-community-3.5.3/data/databases/multiple.dependency.db
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8080

data:
  project_config: src/main/resources/project/test.json
  dynamic_analyse: true
  git_analyse: true
  lib_analyse: true
  clone_analyse: true

  neo4j:
    delete: true
    path: D:/software/neo4j-community-3.5.3/data/databases/multiple.dependency.db

  test: this property is for YamlUtilsTest
