spring:
  data:
    neo4j:
      username: neo4j
      password: 19970129Fan
      uri: bolt://localhost:7687
#      uri: http://localhost:7474
      # embedded
#      uri: file:///D:/fan/Users/Thinkpad/neo4j-community-3.5.3-windows/neo4j-community-3.5.3/data/databases/multiple.dependency.db
  thymeleaf:
    cache: false 
server:
   port: 8080

data:
   delete: true
   code:
      rootPath: D:\multiple-dependency-project\train-ticket
#      rootPath: D:\git\SimpleTest
#      rootPath: D:\multiple-dependency-project\depends
      # 0为当前目录为一个项目   
      depth: 1
      excludes: []
      cppIncludes: []
#      path: D:\git\halo-1.1.3-beta.1
#      path: D:\git\multi-dependency
#      path: C:\Users\Thinkpad\Desktop\0416\all\cassandra-3.0.0\cassandra-cassandra-3.0.0
#      path: C:\Users\fan\Downloads\hadoop-trunk
#      path: D:\multiple-dependency-project\depends-0.9.5c
#      path: D:\git\bcrypt-1.1
#      path: D:\git\Sockets-2.3.9.9
#      path: D:\multiple-dependency-project\train-ticket
#      path: D:\git\SimpleTest
#      path: D:\git\redis-5.0.5
#      path: D:\multiple-dependency-project\Sockets-2.3.9.9
#      path: D:\multiple-dependency-project\bash-5.0
#      path: D:\multiple-dependency-project\tabix     
      languages: [java]
      #, cpp]
      platform: windows
   dynamic:
      analyse: false
#      directory_root_path: src/main/resources/dynamic/kieker
#      directory_root_path: src/main/resources/dynamic/valgrind
      directory_root_path: src/main/resources/dynamic/stub/logs
#      dynamic_java_file_suffix: [.dat]
      dynamic_java_file_suffix: [.log]
      dynamic_cpp_file_suffix: [.dot, .out]
      dynamic_mark_suffix: .mark
   build:   
      analyse: false
      directory_root_path: src/main/resources/build
   neo4j:
      # batchInserter要插入的数据库
      path: D:/neo4j-community-3.5.3-windows/neo4j-community-3.5.3/data/databases/multiple.dependency.db
   
   test: this property is for YamlUtilsTest
     
