spring:
  data:
    neo4j:
      username: neo4j
      password: 123456
      uri: bolt://localhost:7687
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8080

data:
  project_config: src/main/resources/project/template.json
  dynamic_analyse: true
  git_analyse: true
  lib_analyse: true
  clone_analyse: true

  neo4j:
    delete: true
    # batchInserter要插入的数据库
    path: D:/neo4j-community-3.5.16/data/databases/multiple.dependency.db

  serialize_path: C:/Users/SongJee/Desktop/serializePath/RepositoryService.txt

  test: this property is for YamlUtilsTest
