spring:
  data:
    neo4j:
      username: neo4j
      password: 123456
#      uri: bolt://localhost:7687
#      uri: http://localhost:7474
      # embedded
      uri: file:///software/neo4j-community-3.5.3/data/databases/multiple.dependency.db
server:
   port: 8080
   
data:
   delete: true
   code:
#      path: D:\git\halo-1.1.3-beta.1
#      path: D:\my_data\SDTeam\depends\depends
      path: D:\my_data\c_demo\tabix
#      language: java
#      path: D:\git\bcrypt-1.1
      language: cpp
      platform: windows
   dynamic:
      analyse: true
      directory_root_path: src/main/resources/dynamic/kieker
#      directory_root_path: src/main/resources/dynamic/valgrind
      dynamic_java_file_suffix: [.dat]
      dynamic_cpp_file_suffix: [.dot, .out]
      dynamic_mark_suffix: .mark
   build:   
      analyse: true
      directory_root_path: src/main/resources/build
   neo4j:
      # batchInserter要插入的数据库
      path: D:\software\neo4j-community-3.5.3\data\databases\multiple.dependency.db
   
   test: this property is for YamlUtilsTest
      