spring:
  data:
    neo4j:
      username: neo4j
      password: 123
      uri: bolt://localhost:7687
  #      password: admin
  #      uri: bolt://10.176.34.86:9687
  #
  #      password: admin
  #      uri: bolt://10.176.34.83:9687
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8080

config:
  starter:
    hierarchical_cluster: false
    loose_degree: false
    insert_nodes: true
    insert_relations: true
    cochange: false
    depends_on: true
    clone_group: false
    module_clone: false
    aggregation_clone: false
    smell: false
    modularity: false
    coupling: true
    package_depth: true
    export_cyclic_dependency: false
data:

  project_config: C:/Dev/DependencyAnalysis/Tools/issuetracker01.json
#  project_config: C:/Dev/DependencyAnalysis/Tools/issuetracker05.json
#  project_config: C:/Dev/DependencyAnalysis/Tools/flink.json
  project_analyse_threads_count: 20
  dynamic_analyse: false
  git_analyse: false
  lib_analyse: false
  clone_analyse: false
  alltag_analyse: false
  diff_analyse: false
  snapshot_analyse: false


  neo4j:
    delete: true
    # batchInserter要插入的数据库
    data_path: C:/App/neo4j-community-4.2.19/data
#    data_path: C:/App/neo4j-community-4.4.10/data
#    database_name: issuetracker01
#    database_name: issuetracker05
    database_name: tomcat-calm
#    database_name: flink.db
  #    database_name: multi.dependency.all.db
  #    database_name: multi.dependency.atlas.db

  serialize_path: C:/Dev/DependencyAnalysis/Result/tomcat-calm/source-tomcat-calm.txt
#  serialize_path: C:/Dev/DependencyAnalysis/Result/flink.txt
#  serialize_path: C:/Dev/DependencyAnalysis/Result/issuetracker01.txt
#  serialize_path: C:/Dev/DependencyAnalysis/Result/issuetracker05.txt
  coupling_value_path: C:/Dev/DependencyAnalysis/Result/coupling_value_export_tomcat.csv
  anonymization: false
  batch_serialize: true

  test: this property is for YamlUtilsTest
