package cn.edu.fudan.se.multidependency.model.relation;

import org.neo4j.graphdb.RelationshipType;

public enum RelationType implements RelationshipType {
	CONTAIN(RelationType.str_CONTAIN),

	DEPENDENCY_TYPE_IMPLEMENTS_TYPE(RelationType.str_DEPENDENCY_TYPE_IMPLEMENTS_TYPE),
	DEPENDENCY_TYPE_EXTENDS_TYPE(RelationType.str_DEPENDENCY_TYPE_EXTENDS_TYPE),
	DEPENDENCY_FILE_IMPORT_FUNCTION(RelationType.str_DEPENDENCY_FILE_IMPORT_FUNCTION),
	DEPENDENCY_FILE_IMPORT_TYPE(RelationType.str_DEPENDENCY_FILE_IMPORT_TYPE),
	DEPENDENCY_FILE_IMPORT_VARIABLE(RelationType.str_DEPENDENCY_FILE_IMPORT_VARIABLE),
	DEPENDENCY_FILE_INCLUDE_FILE(RelationType.str_DEPENDENCY_FILE_INCLUDE_FILE),
	DEPENDENCY_FUNCTION_CALL_FUNCTION(RelationType.str_DEPENDENCY_FUNCTION_CALL_FUNCTION),
	DEPENDENCY_FUNCTION_PARAMETER_TYPE(RelationType.str_DEPENDENCY_FUNCTION_PARAMETER_TYPE),
	DEPENDENCY_FUNCTION_RETURN_TYPE(RelationType.str_DEPENDENCY_FUNCTION_RETURN_TYPE),
	VARIABLE_IS_TYPE(RelationType.str_VARIABLE_IS_TYPE),
	DEPENDENCY_DYNAMIC_FUNCTION_CALL_FUNCTION(RelationType.str_DEPENDENCY_DYNAMIC_FUNCTION_CALL_FUNCTION);

	/**
	 * 结构关系
	 */
	public static final String str_CONTAIN = "CONTAIN";

	/**
	 * 依赖关系
	 */
	public static final String str_DEPENDENCY_TYPE_EXTENDS_TYPE = "DEPENDENCY_TYPE_EXTENDS_TYPE";
	public static final String str_DEPENDENCY_TYPE_IMPLEMENTS_TYPE = "DEPENDENCY_TYPE_IMPLEMENTS_TYPE";
	public static final String str_DEPENDENCY_FILE_IMPORT_FUNCTION = "DEPENDENCY_FILE_IMPORT_FUNCTION";
	public static final String str_DEPENDENCY_FILE_IMPORT_TYPE = "DEPENDENCY_FILE_IMPORT_TYPE";
	public static final String str_DEPENDENCY_FILE_IMPORT_VARIABLE = "DEPENDENCY_FILE_IMPORT_VARIABLE";
	public static final String str_DEPENDENCY_FILE_INCLUDE_FILE = "DEPENDENCY_FILE_INCLUDE_FILE";
	public static final String str_DEPENDENCY_FUNCTION_CALL_FUNCTION = "DEPENDENCY_FUNCTION_CALL_FUNCTION";
	public static final String str_DEPENDENCY_FUNCTION_PARAMETER_TYPE = "DEPENDENCY_FUNCTION_PARAMETER_TYPE";
	public static final String str_DEPENDENCY_FUNCTION_RETURN_TYPE = "DEPENDENCY_FUNCTION_RETURN_TYPE";
	public static final String str_VARIABLE_IS_TYPE = "VARIABLE_IS_TYPE";
	public static final String str_DEPENDENCY_DYNAMIC_FUNCTION_CALL_FUNCTION = "DYNAMIC_FUNCTION_CALL_FUNCTION";

	private String name;

	RelationType(String name) {
		this.name = name;
	}

	public String getName() {
		return name;
	}
}
